# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EqualizerBeta_layout.ui'
#
# Created: Sun Mar 19 19:53:22 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_EqualizerBeta(object):
    def setupUi(self, EqualizerBeta):
        EqualizerBeta.setObjectName("EqualizerBeta")
        EqualizerBeta.resize(862, 513)
        self.verticalLayoutWidget = QtGui.QWidget(EqualizerBeta)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(470, 130, 221, 119))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.outputLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.outputLayout.setContentsMargins(0, 0, 0, 0)
        self.outputLayout.setObjectName("outputLayout")
        self.in_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.in_label.setAutoFillBackground(True)
        self.in_label.setAlignment(QtCore.Qt.AlignCenter)
        self.in_label.setObjectName("in_label")
        self.outputLayout.addWidget(self.in_label)
        self.Input_val = QtGui.QLabel(self.verticalLayoutWidget)
        self.Input_val.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_val.setObjectName("Input_val")
        self.outputLayout.addWidget(self.Input_val)
        self.OUT_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.OUT_label.setAutoFillBackground(True)
        self.OUT_label.setAlignment(QtCore.Qt.AlignCenter)
        self.OUT_label.setObjectName("OUT_label")
        self.outputLayout.addWidget(self.OUT_label)
        self.output_val = QtGui.QLabel(self.verticalLayoutWidget)
        self.output_val.setAlignment(QtCore.Qt.AlignCenter)
        self.output_val.setObjectName("output_val")
        self.outputLayout.addWidget(self.output_val)
        self.selectOutputButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.selectOutputButton.setObjectName("selectOutputButton")
        self.outputLayout.addWidget(self.selectOutputButton)
        self.verticalLayoutWidget_2 = QtGui.QWidget(EqualizerBeta)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(110, 110, 261, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.controlLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.controlLayout.setContentsMargins(0, 0, 0, 0)
        self.controlLayout.setObjectName("controlLayout")
        self.SelectFileLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.SelectFileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectFileLabel.setObjectName("SelectFileLabel")
        self.controlLayout.addWidget(self.SelectFileLabel)
        self.selectFileButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.selectFileButton.setObjectName("selectFileButton")
        self.controlLayout.addWidget(self.selectFileButton)
        self.startbutton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.startbutton.setObjectName("startbutton")
        self.controlLayout.addWidget(self.startbutton)
        self.title = QtGui.QLabel(EqualizerBeta)
        self.title.setEnabled(False)
        self.title.setGeometry(QtCore.QRect(110, 10, 571, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(37)
        font.setWeight(75)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.RichText)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.horizontalLayoutWidget = QtGui.QWidget(EqualizerBeta)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(109, 349, 671, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LowFreqButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.LowFreqButton.setCheckable(True)
        self.LowFreqButton.setObjectName("LowFreqButton")
        self.horizontalLayout.addWidget(self.LowFreqButton)
        self.MidFreqButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.MidFreqButton.setCheckable(True)
        self.MidFreqButton.setObjectName("MidFreqButton")
        self.horizontalLayout.addWidget(self.MidFreqButton)
        self.HighFreqButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.HighFreqButton.setCheckable(True)
        self.HighFreqButton.setChecked(False)
        self.HighFreqButton.setObjectName("HighFreqButton")
        self.horizontalLayout.addWidget(self.HighFreqButton)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(EqualizerBeta)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 390, 671, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.attenuateButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.attenuateButton.setCheckable(True)
        self.attenuateButton.setObjectName("attenuateButton")
        self.horizontalLayout_2.addWidget(self.attenuateButton)
        self.passThroughButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.passThroughButton.setCheckable(True)
        self.passThroughButton.setObjectName("passThroughButton")
        self.horizontalLayout_2.addWidget(self.passThroughButton)
        self.amplifyButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.amplifyButton.setCheckable(True)
        self.amplifyButton.setObjectName("amplifyButton")
        self.horizontalLayout_2.addWidget(self.amplifyButton)
        self.resetButton = QtGui.QPushButton(EqualizerBeta)
        self.resetButton.setGeometry(QtCore.QRect(370, 280, 110, 32))
        self.resetButton.setObjectName("resetButton")
        self.impulseButton = QtGui.QPushButton(EqualizerBeta)
        self.impulseButton.setGeometry(QtCore.QRect(370, 310, 110, 32))
        self.impulseButton.setObjectName("impulseButton")

        self.retranslateUi(EqualizerBeta)
        QtCore.QMetaObject.connectSlotsByName(EqualizerBeta)

    def retranslateUi(self, EqualizerBeta):
        EqualizerBeta.setWindowTitle(QtGui.QApplication.translate("EqualizerBeta", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.in_label.setText(QtGui.QApplication.translate("EqualizerBeta", "INPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.Input_val.setText(QtGui.QApplication.translate("EqualizerBeta", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.OUT_label.setText(QtGui.QApplication.translate("EqualizerBeta", "OUTPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.output_val.setText(QtGui.QApplication.translate("EqualizerBeta", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.selectOutputButton.setText(QtGui.QApplication.translate("EqualizerBeta", "Select Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectFileLabel.setText(QtGui.QApplication.translate("EqualizerBeta", "Select an audio file", None, QtGui.QApplication.UnicodeUTF8))
        self.selectFileButton.setText(QtGui.QApplication.translate("EqualizerBeta", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton.setText(QtGui.QApplication.translate("EqualizerBeta", "Start Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("EqualizerBeta", "Audio Equaliser", None, QtGui.QApplication.UnicodeUTF8))
        self.LowFreqButton.setText(QtGui.QApplication.translate("EqualizerBeta", "Low Frequencies", None, QtGui.QApplication.UnicodeUTF8))
        self.MidFreqButton.setText(QtGui.QApplication.translate("EqualizerBeta", "Mid Frequencies", None, QtGui.QApplication.UnicodeUTF8))
        self.HighFreqButton.setText(QtGui.QApplication.translate("EqualizerBeta", "High Frequencies", None, QtGui.QApplication.UnicodeUTF8))
        self.attenuateButton.setText(QtGui.QApplication.translate("EqualizerBeta", "-40 dB", None, QtGui.QApplication.UnicodeUTF8))
        self.passThroughButton.setText(QtGui.QApplication.translate("EqualizerBeta", "0 dB", None, QtGui.QApplication.UnicodeUTF8))
        self.amplifyButton.setText(QtGui.QApplication.translate("EqualizerBeta", "+40 dB", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("EqualizerBeta", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.impulseButton.setText(QtGui.QApplication.translate("EqualizerBeta", "Impulse Response", None, QtGui.QApplication.UnicodeUTF8))

